FROM node:lts-alpine
WORKDIR /app
CMD ls -l
# COPY package.json /app/
# RUN npm install
# COPY ./ /app/
# EXPOSE 4200
# CMD npm run start

# ENV NODE_VERSION 16.1.0

# RUN apt-get update \
#     && apt-get -y install --no-install-recommends apt-utils 2>&1

# # Verify git and needed tools are installed
# RUN apt-get install -y git procps

# # Remove outdated yarn from /opt and install via package
# # so it can be easily updated via apt-get upgrade yarn

# # Install the Angular CLI
# RUN npm install -g @angular/cli
# RUN npm install -g nx
# # Clean up
# RUN apt-get autoremove -y \
#     && apt-get clean -y \
#     && rm -rf /var/lib/apt/lists/*
# ENV DEBIAN_FRONTEND=dialog
# # Expose port 4250
# EXPOSE 4250
# EXPOSE 9222
